from typing import List, Dict, Optional
from .cypher_query_llm import CypherQueryService
from .context_filter import ContextFilterEmbedding
from langchain_core.prompts import PromptTemplate
from llm_config import get_gemini_llm
from agents.patient_db_agent import PatientQueryEngine
from agents.rag_agent.query_expander import QueryExpander
from config import Config

config = Config()
prompt = PromptTemplate(
    template="""
    Bạn là bác sĩ AI chuyên nghiệp. 
    CHỈ trả lời dựa trên những thông tin trong phần **KIẾN THỨC LIÊN QUAN** 
    MÀ thực sự phù hợp với **THÔNG TIN BỆNH NHÂN** và trực tiếp liên quan tới **CÂU HỎI**. 
    Nếu một thông tin nào đó không liên quan, hãy BỎ QUA, KHÔNG đưa vào câu trả lời.

    THÔNG TIN BỆNH NHÂN:
    {patient_info}

    KIẾN THỨC LIÊN QUAN (đã được lọc):
    {filtered_context}

    CÂU HỎI: {question}

    Hãy đưa ra lời khuyên cụ thể, phù hợp với:
    - Tuổi và giới tính của bệnh nhân
    - Tình trạng sức khỏe hiện tại
    - Tiền sử bệnh lý
    - Chỉ sử dụng thông tin đã nêu ở trên, 
      tuyệt đối KHÔNG suy đoán ngoài nguồn dữ liệu.

    TRẢ LỜI:
    """,
    input_variables=["patient_info", "filtered_context", "question"]
)

class ResponseGenerator:
    def __init__(self, patient_query_engine: PatientQueryEngine):
        self.cypher_query_llm = CypherQueryService()
        self.context_filter = ContextFilterEmbedding()
        self.llm = get_gemini_llm(temperature=0.2)
        self.patient_query_engine = patient_query_engine
        self.query_expander = QueryExpander(config)
    
    def generate_response(self, question: str, patient_id: str, chat_history: Optional[List[Dict[str, str]]] = None):
        # patient profile
        patient_profile = self.patient_query_engine.get_patient_profile(patient_id)
        # query expander
        expanded_result = self.query_expander.expand_query(question, patient_info=patient_profile, mode="kg", chat_history=chat_history)
        expanded_result = expanded_result["expanded_query"]
        question = expanded_result["refined_question"]
        patient_context = expanded_result["patient_context"]

        print("Expanded question: ", question)
        print("Patient context: ", patient_context)

        # context from kg (cypher query generated by llm)
        kg_context = self.cypher_query_llm.retrieve_context_from_kg(question) 

        ### IF the kg context is empty, return "Không có thông tin liên quan"
        if not kg_context:
            return "Không có thông tin liên quan"
        
        # filter context from kg 
        filtered_context = self.context_filter.filter_context(kg_context, patient_context, question)

        ### IF the filtered context is empty, return "Không có thông tin liên quan"
        if not filtered_context:
            return "Không có thông tin liên quan"

        # generate response
        response = self.llm.invoke(prompt.format(patient_info=patient_context, 
                                                filtered_context=filtered_context, 
                                                question=question))

        safety_disclaimer = "\n\n⚠️ **Lưu ý quan trọng:** Thông tin trên chỉ mang tính chất tham khảo và được tạo ra bởi AI. Đây không phải là chẩn đoán y tế chính thức. Bạn nên đi khám bác sĩ chuyên khoa sớm nhất có thể để được thăm khám và điều trị phù hợp."

        return response.content + safety_disclaimer
    