from typing import List, Dict, Optional
from .cypher_query_llm import CypherQueryService
from .context_filter import ContextFilterEmbedding
from llm_config import get_fpt_llm
from agents.patient_db_agent import PatientQueryEngine
from agents.rag_agent.query_expander import QueryExpander
from config import Config
from prompt import medical_cot_prompt
import json

config = Config()
prompt = medical_cot_prompt

class ResponseGenerator:
    def __init__(self, patient_query_engine: PatientQueryEngine):
        self.cypher_query_llm = CypherQueryService()
        self.context_filter = ContextFilterEmbedding()
        self.llm = get_fpt_llm(temperature=0.2)
        self.patient_query_engine = patient_query_engine
        self.query_expander = QueryExpander(config)
    
    def generate_response(self, question: str, patient_id: str, chat_history: Optional[List[Dict[str, str]]] = None):
        # patient profile
        patient_profile = self.patient_query_engine.get_patient_profile(patient_id)
        # query expander
        expanded_result = self.query_expander.expand_query(question, patient_info=patient_profile, mode="kg", chat_history=chat_history)
        expanded_result = expanded_result["expanded_query"]
        question = expanded_result["refined_question"]
        patient_context = expanded_result["patient_context"]

        print("Expanded question: ", question)
        print("Patient context: ", patient_context)

        # context from kg (cypher query generated by llm)
        kg_context = self.cypher_query_llm.retrieve_context_from_kg(question) 

        if not kg_context:
            return "Không có thông tin liên quan"
        
        # filter context from kg 
        filtered_context = self.context_filter.filter_context(kg_context, patient_context, question)

        if not filtered_context:
            return "Không có thông tin liên quan"

        # generate response
        kg_candidates_json = json.dumps(filtered_context, ensure_ascii=False)
        response = self.llm.invoke(prompt.format(
                                                patient_context=patient_context,
                                                kg_candidates=kg_candidates_json,
                                                user_query=question,
                                                history=chat_history))

        # Parse JSON response and extract content
        try:
            # Clean response content and extract JSON
            response_text = response.content.strip()
            if response_text.startswith("```json"):
                response_text = response_text[7:]  # Remove ```json
            if response_text.endswith("```"):
                response_text = response_text[:-3]  # Remove ```
            
            response_json = json.loads(response_text)
            content = response_json.get("step3_action", {}).get("content", "không có thông tin liên quan")
            
        except (json.JSONDecodeError, KeyError) as e:
            print(f"Error parsing JSON response: {e}")
            content = response.content  # Fallback to original content

        safety_disclaimer = "\n\n⚠️ **Lưu ý quan trọng:** Thông tin trên chỉ mang tính chất tham khảo và được tạo ra bởi AI. Đây không phải là chẩn đoán y tế chính thức. Bạn nên đi khám bác sĩ chuyên khoa sớm nhất có thể để được thăm khám và điều trị phù hợp."
        
        return content + safety_disclaimer